# Generated by Django 4.2.3 on 2023-07-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archivos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivo",
            name="archivo",
            field=models.FileField(upload_to="files/"),
        ),
    ]
